import { Tank, ParameterLog, MaintenanceEntry, EquipmentItem } from '@shared/types';

/**
 * Demo data for guest mode
 * Gives users a realistic preview of the app with sample reef tank data
 */

export const DEMO_TANK: Tank = {
  id: 'demo-tank-001',
  name: 'Demo Reef Tank',
  size_gallons: 75,
  type: 'reef',
  setup_date: '2025-06-15',
  notes: 'Sample reef tank to explore AquaXone',
  is_active: true,
  user_id: 'demo-user',
  created_at: '2025-06-15T00:00:00Z',
};

export const DEMO_FRESHWATER_TANK: Tank = {
  id: 'demo-tank-002',
  name: 'Demo Planted Tank',
  size_gallons: 40,
  type: 'freshwater',
  setup_date: '2025-08-01',
  notes: 'Sample freshwater planted tank',
  is_active: true,
  user_id: 'demo-user',
  created_at: '2025-08-01T00:00:00Z',
};

// Generate dates going back from today
function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
}

export const DEMO_LOGS: ParameterLog[] = [
  {
    id: 'demo-log-01',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    log_date: daysAgo(0),
    temp: 78.2,
    ph: 8.25,
    salinity: 35.1,
    alk: 8.8,
    cal: 440,
    mag: 1380,
    no3: 3.5,
    po4: 0.04,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-log-02',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    log_date: daysAgo(3),
    temp: 77.8,
    ph: 8.2,
    salinity: 35.0,
    alk: 8.5,
    cal: 435,
    mag: 1370,
    no3: 4.0,
    po4: 0.05,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-log-03',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    log_date: daysAgo(7),
    temp: 78.0,
    ph: 8.18,
    salinity: 35.2,
    alk: 8.3,
    cal: 430,
    mag: 1360,
    no3: 5.0,
    po4: 0.06,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-log-04',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    log_date: daysAgo(10),
    temp: 78.5,
    ph: 8.22,
    salinity: 35.0,
    alk: 9.0,
    cal: 445,
    mag: 1390,
    no3: 2.5,
    po4: 0.03,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-log-05',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    log_date: daysAgo(14),
    temp: 77.6,
    ph: 8.15,
    salinity: 34.8,
    alk: 8.0,
    cal: 425,
    mag: 1350,
    no3: 6.0,
    po4: 0.08,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-log-06',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    log_date: daysAgo(17),
    temp: 78.1,
    ph: 8.20,
    salinity: 35.1,
    alk: 8.6,
    cal: 438,
    mag: 1375,
    no3: 4.5,
    po4: 0.05,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-log-07',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    log_date: daysAgo(21),
    temp: 77.9,
    ph: 8.12,
    salinity: 35.0,
    alk: 7.8,
    cal: 420,
    mag: 1340,
    no3: 7.0,
    po4: 0.09,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_MAINTENANCE: MaintenanceEntry[] = [
  {
    id: 'demo-maint-01',
    due_date: daysAgo(-2), // upcoming
    task: 'water_change',
    description: '10% water change',
    status: 'pending',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-maint-02',
    due_date: daysAgo(1), // overdue
    task: 'dose_alk',
    description: 'Dose 10ml alkalinity',
    status: 'pending',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-maint-03',
    due_date: daysAgo(3),
    task: 'glass_clean',
    description: 'Clean front and side glass',
    status: 'completed',
    completed_date: daysAgo(3),
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-maint-04',
    due_date: daysAgo(7),
    task: 'water_change',
    description: '15% water change with Red Sea salt',
    status: 'completed',
    completed_date: daysAgo(7),
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-maint-05',
    due_date: daysAgo(14),
    task: 'filter_clean',
    description: 'Clean filter socks and protein skimmer',
    status: 'completed',
    completed_date: daysAgo(13),
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-maint-06',
    due_date: daysAgo(-5), // upcoming
    task: 'feed',
    description: 'Coral feeding - Reef Roids',
    status: 'pending',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    created_at: new Date().toISOString(),
  },
];

export const DEMO_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'demo-equip-01',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    name: 'Return Pump',
    category: 'circulation',
    brand: 'EcoTech Marine',
    model: 'Vectra L2',
    cost: 449,
    purchase_date: '2025-06-15',
    warranty_until: '2028-06-15',
    power_watts: 65,
    is_active: true,
    notes: 'Running at 70% speed via Mobius app',
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'demo-equip-02',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    name: 'Protein Skimmer',
    category: 'skimmer',
    brand: 'Reef Octopus',
    model: 'Regal 200-S',
    cost: 389,
    purchase_date: '2025-06-15',
    warranty_until: '2027-06-15',
    power_watts: 30,
    is_active: true,
    notes: 'Cup cleaned weekly, pulls dark green skimmate',
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'demo-equip-03',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    name: 'LED Light Bar',
    category: 'lighting',
    brand: 'AI',
    model: 'Hydra 64 HD',
    cost: 599,
    purchase_date: '2025-07-01',
    warranty_until: '2028-07-01',
    power_watts: 135,
    is_active: true,
    notes: 'AB+ schedule, peaks at 80% intensity',
    created_at: '2025-07-01T00:00:00Z',
  },
  {
    id: 'demo-equip-04',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    name: 'Wavemaker (Left)',
    category: 'circulation',
    brand: 'EcoTech Marine',
    model: 'VorTech MP40',
    cost: 499,
    purchase_date: '2025-06-20',
    warranty_until: '2028-06-20',
    power_watts: 38,
    is_active: true,
    notes: 'Reef Crest mode, anti-sync with right side',
    created_at: '2025-06-20T00:00:00Z',
  },
  {
    id: 'demo-equip-05',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    name: 'Dosing Pump',
    category: 'dosing',
    brand: 'Neptune Systems',
    model: 'DOS',
    cost: 299,
    purchase_date: '2025-08-10',
    warranty_until: '2027-08-10',
    power_watts: 5,
    is_active: true,
    notes: 'Dosing BRS 2-part: 70ml alk + 65ml calcium daily',
    created_at: '2025-08-10T00:00:00Z',
  },
  {
    id: 'demo-equip-06',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    name: 'Heater',
    category: 'heating',
    brand: 'Eheim',
    model: 'Jäger 200W',
    cost: 39,
    purchase_date: '2025-06-15',
    warranty_until: '2027-06-15',
    power_watts: 200,
    is_active: true,
    notes: 'Set to 77.5°F, controlled by Apex failsafe',
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: 'demo-equip-07',
    tank_id: 'demo-tank-001',
    user_id: 'demo-user',
    name: 'Test Kit',
    category: 'testing',
    brand: 'Hanna Instruments',
    model: 'Checker Bundle',
    cost: 189,
    purchase_date: '2025-07-15',
    is_active: true,
    notes: 'Alk, Calcium, Phosphorus checkers',
    created_at: '2025-07-15T00:00:00Z',
  },
];

export const DEMO_TANKS = [DEMO_TANK, DEMO_FRESHWATER_TANK];
